# Generated by Django 5.2.14 on 2026-09-23 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-date']},
        ),
        migrations.CreateModel(
            name='SaleChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('fields_changed', models.JSONField(blank=True, default=dict)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='sales.sale')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_change_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
