# Generated by Django 5.2.14 on 2026-09-28 12:40

from django.db import migrations

# PRE-CONDIÇÃO (rodar antes de aplicar esta migração):
#
#   SELECT count(*) FROM sales_sale
#    WHERE invoice_number <> LPAD(id::text, 6, '0');
#
# Precisa devolver 0. A coluna é determinística a partir do id e era preenchida
# pelo Sale.save() logo após o INSERT, que é exatamente o statement que esta
# mudança elimina. Divergência indica dado escrito fora do fluxo normal e
# precisa ser investigada antes de seguir.


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_cancellation_reason_sale_cancelled_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='invoice_number',
        ),
    ]
