# Generated by Django 5.2.14 on 2026-09-28 12:50

from django.db import migrations, models

# Índice para o relatório de comissões (filtro por intervalo de data e
# ordenação por -date). O CREATE INDEX padrão do Django segura um lock que
# bloqueia escritas na tabela enquanto roda; se a tabela de vendas estiver
# grande em produção, prefira criar o índice com CREATE INDEX CONCURRENTLY
# (django.contrib.postgres.operations.AddIndexConcurrently) antes de aplicar
# esta migração.


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_sale_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
